source 'https://rubygems.org'

gem 'rails', ENV['RAILS_VERSION']

platforms :jruby do
  gem 'jdbc-sqlite3'
  gem 'activerecord-jdbcsqlite3-adapter'
end

platforms :mri do
  gem 'sqlite3'
end

gem 'ballot', path: '../../..'
